version: '3.9'
   
networks:
  stack-inbound:
    name: ${APPLICATION_DEPLOY_NETWORK_NAME}
    external: true
    
services:
  debian:
    image: ${APPLICATION_DEPLOY_IMAGE}
    hostname: ${APPLICATION_DEPLOY_HOSTNAME}
    env_file:
      - ${APPLICATION_DEPLOY_ENV_FILE}
    environment:
      - SERVER_CONTEXT_PATH=${APPLICATION_DEPLOY_CONTEXT_PATH}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}:/home-host
      - ${APPLICATION_DEPLOY_CONF_DIR}/run:/opt/run
      - ${APPLICATION_DEPLOY_DATA_DIR}:/app/data
      - ${APPLICATION_DEPLOY_BACKUP_DIR}:/app/backup
    ports:
      - target: ${APPLICATION_DEPLOY_PORT}
        protocol: tcp
        mode: ingress
    deploy:
      mode: ${APPLICATION_DEPLOY_MODE}
      replicas: ${APPLICATION_DEPLOY_REPLICAS}
      placement:
        constraints:
          - ${APPLICATION_DEPLOY_NODE}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.http.routers.${APPLICATION_NAME}.rule=Host(`${APPLICATION_DEPLOY_DNS}`)"
        - "traefik.http.routers.${APPLICATION_NAME}.service=${APPLICATION_NAME}"
        - "traefik.http.services.${APPLICATION_NAME}.loadbalancer.server.port=${APPLICATION_DEPLOY_PORT}"
        - "traefik.docker.network=${APPLICATION_DEPLOY_NETWORK_NAME}"
    entrypoint: sh /opt/run
    networks:
      - stack-inbound