version: '3.9'

#ref
#   https://community.traefik.io/t/help-in-tcp-configure-of-traefik-mapped-postgresql-container-hostsni/13386/6
   
networks:
  stack-inbound:
    name: ${APPLICATION_DEPLOY_NETWORK_NAME}
    external: true
    
services:
  db:
    image: ${APPLICATION_DEPLOY_IMAGE}
    hostname: ${APPLICATION_DEPLOY_HOSTNAME}
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - ${APPLICATION_DEPLOY_DATA_DIR}:/postgresql/pg/data:rw
      - ${APPLICATION_DEPLOY_BACKUP_DIR}:/postgresql/pg/backup:rw
    env_file:
      - ${APPLICATION_NAME}.env
    environment:
      # - POSTGRES_USER=${APPLICATION_DB_USER}
      # - POSTGRES_PASSWORD=${APPLICATION_DB_PASSWORD}
      - PGDATA=/postgresql/pg/data
    ports:
      - target: 5432
        published: ${APPLICATION_DEPLOY_PORT}
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - ${APPLICATION_DEPLOY_NODE}
      resources:
        limits:
          cpus: "${STACK_CPU_DEFAULT}"
          memory: ${STACK_MEMORY_DEFAULT}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - stack-inbound
