version: '3.9'

#ref
#   https://community.traefik.io/t/help-in-tcp-configure-of-traefik-mapped-postgresql-container-hostsni/13386/6
   
networks:
  stack-inbound:
    name: ${APPLICATION_DEPLOY_NETWORK_NAME}
    external: true
    
services:
  db:
    image: ${APPLICATION_DEPLOY_IMAGE}
    hostname: ${APPLICATION_DEPLOY_HOSTNAME}
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - ${APPLICATION_DEPLOY_DATA_DIR}:/postgresql/pg/data:rw
      - ${APPLICATION_DEPLOY_BACKUP_DIR}:/postgresql/pg/backup:rw
    environment:
      - POSTGRES_USER=${APPLICATION_DB_USER}
      - POSTGRES_PASSWORD=${APPLICATION_DB_PASSWORD}
      - PGDATA=/postgresql/pg/data
    ports:
      - target: 5432
        published: ${APPLICATION_DEPLOY_PORT}
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager
      resources:
          limits:
            cpus: ${STACK_CPU_DEFAULT}
            memory: ${STACK_MEMORY_DEFAULT}
      restart_policy:
        condition: on-failure
      # labels:
      #   - "traefik.enable=true"
      #   - "traefik.docker.network=${APPLICATION_DEPLOY_NETWORK_NAME}"
      #   - "traefik.tcp.routers.${APPLICATION_NAME}.rule=Host(`${APPLICATION_DEPLOY_DNS}`)"
      #   - "traefik.tcp.routers.${APPLICATION_NAME}.entryPoints=postgres"
      #   - "traefik.tcp.routers.${APPLICATION_NAME}.service=${APPLICATION_NAME}"
      #   - "traefik.tcp.services.${APPLICATION_NAME}.loadbalancer.server.port=5432"

    networks:
      - stack-inbound