version: '3.9'
   
networks:
  stack-inbound:
    name: ${STACK_NETWORK_INBOUND}
    external: true
    
services:
  postgres:
    image: ${APPLICATION_DEPLOY_IMAGE}
    hostname: ${APPLICATION_DEPLOY_HOSTNAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${POSTGRES_DATA}:/postgresql/pg/data
      - ${POSTGRES_BACKUP}:/backup
      - ${STACK_APPLICATIONS_CONFIG_DIR}/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    #env_file:
    #  - ${BUILD_APP_ENV_FILE}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - target: 5432
        protocol: tcp
        mode: ingress
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager
      resources:
          limits:
            cpus: ${STACK_CPU_DEFAULT}
            memory: ${STACK_MEMORY_DEFAULT}
      restart_policy:
        condition: on-failure
    networks:
      - stack-inbound