version: '3.9'

#ref
#   https://community.traefik.io/t/help-in-tcp-configure-of-traefik-mapped-postgresql-container-hostsni/13386/6
   
networks:
  stack-inbound:
    name: ${APPLICATION_DEPLOY_NETWORK_NAME}
    external: true
    
services:
  db:
    image: ${APPLICATION_DEPLOY_IMAGE}
    hostname: ${APPLICATION_DEPLOY_HOSTNAME}
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - ${APPLICATION_DEPLOY_DATA_DIR}:/postgresql/pg/data
      - ${APPLICATION_DEPLOY_BACKUP_DIR}:/postgresql/pg/backup
    environment:
      - POSTGRES_USER=${APPLICATION_DB_USER}
      - POSTGRES_PASSWORD=${APPLICATION_DB_PASSWORD}
      - PGDATA=/postgresql/pg/data
    ports:
      - target: ${APPLICATION_DEPLOY_PORT}
        protocol: tcp
        mode: ingress
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager
      resources:
          limits:
            cpus: ${STACK_CPU_DEFAULT}
            memory: ${STACK_MEMORY_DEFAULT}
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=${APPLICATION_DEPLOY_NETWORK_NAME}"
        - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.postgres.entryPoints=postgres"
        - "traefik.tcp.routers.postgres.service=${APPLICATION_NAME}"
        - "traefik.tcp.services.postgres.loadbalancer.server.port=${APPLICATION_DEPLOY_PORT}"

    networks:
      - stack-inbound