version: '3.9'
   
networks:
  stack-inbound:
    name: inbound
    external: true

services:
  app:
    image: ${APPLICATION_DEPLOY_IMAGE}
    hostname: ${APPLICATION_DEPLOY_HOSTNAME}
    env_file:
      - ${APPLICATION_DEPLOY_ENV_FILE}
    volumes:
      - ${APPLICATION_DEPLOY_DATA_DIR}/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - target: ${APPLICATION_DEPLOY_PORT}
        protocol: tcp
        mode: ingress
    deploy:
      mode: ${APPLICATION_DEPLOY_MODE}
      replicas: ${APPLICATION_DEPLOY_REPLICAS}
      placement:
        constraints:
          - ${APPLICATION_DEPLOY_NODE}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.http.routers.${APPLICATION_NAME}.rule=Host(`${APPLICATION_DEPLOY_DNS}`)"
        - "traefik.http.routers.${APPLICATION_NAME}.service=${APPLICATION_NAME}"
        - "traefik.http.services.${APPLICATION_NAME}.loadbalancer.server.port=${APPLICATION_DEPLOY_PORT}"
        - "traefik.docker.network=${APPLICATION_DEPLOY_NETWORK_NAME}"
    networks:
      - stack-inbound
