version: '3.9'
   
networks:
  stack-inbound:
    name: ${APPLICATION_DEPLOY_NETWORK_NAME}
    external: true

services:
  app:
    image: ${APPLICATION_DEPLOY_IMAGE}
    hostname: ${APPLICATION_DEPLOY_HOSTNAME}
    volumes:
      - ${PUBLIC_LIB_DIR}/qt/${QT_VERSION}:/home/debian/qt
      - ${APPLICATION_DEPLOY_DATA_DIR}:/storage/data:rw
      - ${APPLICATION_DEPLOY_BACKUP_DIR}:/storage/backup:rw
    env_file:
      - ${APPLICATION_NAME}.env
    environment:
      QT_DEBUG_PLUGINS: ${QT_DEBUG_PLUGINS}
    deploy:
      mode: ${APPLICATION_DEPLOY_MODE}
      replicas: ${APPLICATION_DEPLOY_REPLICAS}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.http.routers.${APPLICATION_NAME}.rule=Host(`${APPLICATION_DEPLOY_DNS}`)"
        - "traefik.http.routers.${APPLICATION_NAME}.service=${APPLICATION_NAME}"
        - "traefik.http.services.${APPLICATION_NAME}.loadbalancer.server.port=${APPLICATION_DEPLOY_PORT}"
        - "traefik.docker.network=${APPLICATION_DEPLOY_NETWORK_NAME}"
    networks:
      - stack-inbound
