version: '3.9'

#estudar no futuro
#   ref
#     https://docs.docker.com/desktop/wasm/  
#     https://docs.docker.com/desktop/containerd/
   
networks:
  stack-inbound:
    name: ${APPLICATION_DEPLOY_NETWORK_NAME}
    external: true

services:
  app:
    image: ${APPLICATION_DEPLOY_IMAGE}
    hostname: ${APPLICATION_DEPLOY_HOSTNAME}
    env_file:
      - ${APPLICATION_NAME}.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: ${APPLICATION_DEPLOY_MODE}
      replicas: ${APPLICATION_DEPLOY_REPLICAS}
      placement:
        constraints:
          - ${APPLICATION_DEPLOY_NODE}
      resources:
        limits:
          cpus: "${STACK_CPU_DEFAULT}"
          memory: ${STACK_MEMORY_DEFAULT}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.http.routers.${APPLICATION_NAME}.rule=Host(`${APPLICATION_DEPLOY_DNS}`)
        - traefik.http.routers.${APPLICATION_NAME}.service=${APPLICATION_NAME}
        - traefik.http.routers.${APPLICATION_NAME}.tls=true
        - traefik.http.services.${APPLICATION_NAME}.loadbalancer.server.port=${APPLICATION_DEPLOY_PORT}

        - traefik.http.routers.${APPLICATION_NAME}_pub.rule=Host(`${APPLICATION_DEPLOY_DNS_PUBLIC}`)
        - traefik.http.routers.${APPLICATION_NAME}_pub.service=${APPLICATION_NAME}_pub
        - traefik.http.routers.${APPLICATION_NAME}_pub.tls=true
        - traefik.http.services.${APPLICATION_NAME}_pub.loadbalancer.server.port=${APPLICATION_DEPLOY_PORT}

        - traefik.docker.network=${APPLICATION_DEPLOY_NETWORK_NAME}
    networks:
      - stack-inbound